# Generated by Django 6.0.3 on 2026-03-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='reporting_to',
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('CHAIRMAN', 'Chairman'), ('MD', 'Managing Director'), ('DIRECTOR', 'Director'), ('HOD', 'Department Head'), ('MANAGER', 'Manager'), ('TL', 'Team Leader'), ('HR', 'HR'), ('ACCOUNTS', 'Accounts'), ('TECHNICAL', 'Technical'), ('MARKETING', 'Marketing'), ('BPO', 'BPO'), ('PRO', 'PRO'), ('PRODUCTION', 'Production'), ('SECURITY', 'Security'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
