# Generated by Django 6.0.3 on 2026-04-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_joining_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('CHAIRMAN', 'Chairman'), ('MD', 'Managing Director'), ('DIRECTOR', 'Director'), ('HOD', 'Department Head'), ('MANAGER', 'Manager'), ('TL', 'Team Leader'), ('HR', 'HR'), ('ACCOUNTS', 'Accounts'), ('TECHNICAL', 'Technical'), ('MARKETING', 'Marketing'), ('SALES', 'Sales'), ('BPO', 'BPO'), ('PRO', 'PRO'), ('PRODUCTION', 'Production'), ('SECURITY', 'Security'), ('LEGAL', 'Legal'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
    ]
